### ISSUE TITLE
not working in 1.12.2

### ISSUE THREAD

**Issue by eheimer** [JimiIT92/UniverseGuard2#1]
Brand new clean server with:

forge 1.12.2 - 14.23.1.2555 
spongeforge-1.12.2-2555-7.0.0-BETA-2758.jar.  
UniverseGuard-2.0.jar

```
[21:51:49] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'rg' for source EntityPlayerMP['MathiasCowleyEsq'/320, l='world', x=189.04, y=71.54, z=171.35]: org/spongepowered/api/data/meta/ItemEnchantment
java.lang.NoClassDefFoundError: org/spongepowered/api/data/meta/ItemEnchantment
        at com.universeguard.utils.InventoryUtils.getSelector(InventoryUtils.java:37) ~[InventoryUtils.class:?]
        at com.universeguard.command.RegionExecutor.execute(RegionExecutor.java:35) ~[RegionExecutor.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:176) ~[ChildCommandElementExecutor.class:1.12.2-2555-7.0.0-BETA-2758]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:360) ~[CommandSpec.class:1.12.2-2555-7.0.0-BETA-2758]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-2555-7.0.0-BETA-2758]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:321) [SpongeCommandManager.class:1.12.2-2555-7.0.0-BETA-2758]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) [PacketUtil.class:1.12.2-2555-7.0.0-BETA-2758]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkf000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-2555-7.0.0-BETA-2758]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zih000(MinecraftServer.java:4008) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.data.meta.ItemEnchantment
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
        ... 24 more
Caused by: java.lang.NullPointerException
```

**Comment by JimiIT92** [comment]
Looks like the ItemEnchantment class is gone in 1.12. Will see what replaced it soon :)

**Comment by eheimer** [comment]
I'm not sure if this is thought to be fixed, but I wanted to let you know I just cloned the repo and built it and am still getting errors related to the ItemEnchantment class:

```
[20:12:03] [Server thread/ERROR] [Sponge]: Could not pass InteractBlockEvent$Secondary$MainHand$Impl to Plugin{id=universeguard, name=Universe Guard 2, version=2.6, description=An easy to use world protection plugin for Sponge, authors=[Minehendrix], source=/home/eric/minecraft/./mods/plugins/UniverseGuard-2.6.jar}
java.lang.NoClassDefFoundError: org/spongepowered/api/data/meta/ItemEnchantment
        at com.universeguard.utils.InventoryUtils.getSelector(InventoryUtils.java:37) ~[InventoryUtils.class:?]
        at com.universeguard.utils.InventoryUtils.isSelector(InventoryUtils.java:49) ~[InventoryUtils.class:?]
        at com.universeguard.event.EventRegionSelect.setPoint(EventRegionSelect.java:62) ~[EventRegionSelect.class:?]
        at com.universeguard.event.EventRegionSelect.onRightClick(EventRegionSelect.java:49) ~[EventRegionSelect.class:?]
        at org.spongepowered.common.event.listener.MainHandListener_EventRegionSelect_onRightClick46.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2555-7.0.0-BETA-2758]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:316) [SpongeModEventManager.class:1.12.2-2555-7.0.0-BETA-2758]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:295) [SpongeModEventManager.class:1.12.2-2555-7.0.0-BETA-2758]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345) [SpongeModEventManager.class:1.12.2-2555-7.0.0-BETA-2758]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:333) [SpongeModEventManager.class:1.12.2-2555-7.0.0-BETA-2758]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:198) [SpongeImpl.class:1.12.2-2555-7.0.0-BETA-2758]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:639) [SpongeCommonEventFactory.class:1.12.2-2555-7.0.0-BETA-2758]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:618) [SpongeCommonEventFactory.class:1.12.2-2555-7.0.0-BETA-2758]
        at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:254) [PacketUtil.class:1.12.2-2555-7.0.0-BETA-2758]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:93) [PacketUtil.class:1.12.2-2555-7.0.0-BETA-2758]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkf000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-2555-7.0.0-BETA-2758]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zih000(MinecraftServer.java:4008) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

```

**Comment by Brycey92** [comment]
Not sure why this was closed, but from your log, it looks like you're still having issues. I'll reopen the issue.

**Comment by JimiIT92** [comment]
As i mentioned before, 1.12.2 version is still in development. I closed this issue because there is a dedicated API7 repository here https://github.com/JimiIT92/UniverseGuardAPI7  (the build is still not working and code has errors)  ;)

**Comment by Brycey92** [comment]
Ah. It would be better to have both versions under the same repository with different branches, though. I'll close the issue for now until and unless you move the code to a branch on this repo.

**Comment by JimiIT92** [comment]
Released API7 version for MC-1.12.2. Read more at [https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87)
